### ISSUE TITLE
[Server] - Setup Firebase Database for NFT Tracking & Adding

### ISSUE THREAD

**Issue by SamratSahoo** [gtfintechlab/Universal-NFT-Vector-Database#1]
## EDIT: We no longer need `erc_721_ethereum_nfts` and `erc_721_ethereum_contracts`. Check `client/src/utils/Types.tsx` for updated models and enums in the `samrat/7-task-queue-process` branch

We need a method to allow us to keep track of all of the NFTs and contracts added to the vector database to ensure our database does not end up with duplicate vectors of the same NFT. 

We will also want to mock a task queue in the database so that we can continuously add NFTs to the database. You will need to ask Samrat for access to the Firebase project and any Firebase API keys / Secrets. 

All endpoints written will need to be written in `server/api.ts`

## Acceptance Criteria

**Firebase Criteria:**
- [x] Create a collection called `all_nfts` 
- [x] Create a collection called `all_contracts`
- [ ] Create a collection called `erc_721_ethereum_nfts` 
- [ ] Create a collection called `erc_721_ethereum_contracts`
---
**ExpressJS / Server Criteria:**
- [x] Write an API Endpoint that will add NFT data (a new document) to `all_nfts` --> Ensure added data adheres to the NFT Model Provided
 - API Route: `/api/nfts/addAll`
 - Request Body: 
```
{ 
    data: Object // data is a dictionary that follows the NFT Model
}
```
   - Successful Response:
```
// 200 Status Code
{ 
    success: boolean,
    data: Object         // data that was added to the database 
}
```
    
-  Failed Response:
```
//  400 Access Code
{
    success: boolean,
    error: string
}
```
- [ ] Write an API Endpoint that will add NFT data (a new document) to `erc_721_ethereum_nfts` --> Ensure added data adheres to the NFT Model Provided
 - API Route: `/api/nfts/addErc721`
 - Request Body: 
```
{ 
    data: Object // data is a dictionary that follows the NFT Model
}
```
   - Successful Response:
```
// 200 Status Code
{ 
    success: boolean,
    data: Object         // data that was added to the database 
}
```
    
-  Failed Response:
```
//  400 Access Code
{
    success: boolean,
    error: string
}
```
- [ ] Write an API Endpoint that will add contract data (a new document) to `erc_721_ethereum_contracts` --> Ensure added data adheres to the contract Model Provided
 - API Route: `/api/contracts/addErc721`
 - Request Body: 
```
{ 
    data: Object // data is a dictionary that follows the Contract Model
}
```
   - Successful Response:
```
// 200 Status Code
{ 
    success: boolean,
    data: Object         // data that was added to the database 
}
```
    
-  Failed Response:
```
//  400 Access Code
{
    success: boolean,
    error: string
}
```
- [x] Write an API Endpoint that will add contract data (a new document) to `all_contracts` --> Ensure added data adheres to the contract Model Provided
 - API Route: `/api/contracts/addAll`
 - Request Body: 
```
{ 
    data: Object // data is a dictionary that follows the Contract Model
}
```
   - Successful Response:
```
// 200 Status Code
{ 
    success: boolean,
    data: Object         // data that was added to the database 
}
```
-  Failed Response:
```
//  400 Access Code
{
    success: boolean,
    error: string
}
```
- [x] Write an API Endpoint that will add data (a new document) to `task_queue` --> Ensure added data adheres to the task queue item Model Provided
 - API Route: `/api/taskQueue/add`
 - Request Body: 
```
{ 
    data: Object // data is a dictionary that follows the TaskQueueItem Model
}
```
   - Successful Response:
```
// 200 Status Code
{ 
    success: boolean,
    data: Object         // data that was added to the task queue
}
```
-  Failed Response:
```
//  400 Access Code
{
    success: boolean,
    error: string
}
```
## Models

**Contract:**
```
Contract{
    id: string,
    address: string,
    name: string,
}
```
**NFT:**
```
NFT {
    id: string, 
    transactionId: string,
    contractAddress: string,
    mintTime: Date,
    tokenId: number,
    owner: string, 
    tokenURI: string,
}
```

## Notes
- Cover edge cases / potential errors as you see fit; add comments when covering these so I know what each case is. We will modify these cases when reviewing code
