### ISSUE TITLE
[Design] - Design an Admin Dashboard

### ISSUE THREAD

**Issue by SamratSahoo** [gtfintechlab/Universal-NFT-Vector-Database#2]
## What / Why?

We need an admin dashboard to have easy control over adding contracts into the Task Queue, and keeping track of analytics (i.e. total NFTs added, total NFT Contracts added, etc). Before we can create this, we need a basic design on Figma. Was thinking we could create something elegant but also simple like [Attu](https://zilliz.com/products/attu). 

## Acceptance Criteria
**Overall Analytics for Dashboard:**
- [x] Total number of NFTs in the Vector Database
- [x] Total Number of Smart Contracts we have added to the Database

**Chain / NFT Standard Analytics for Dashboard:**
- [x] Number of ERC 721 Tokens in Database
- [x] Number of ERC 1155 Tokens in Database
- [x] Number of Ethereum NFTs in Database

**Task Queue Information for Dashboard:**
- [x] Smart Contracts currently in the task queue waiting to be processed for all NFTs
- [x] Individual NFTs currently in the task queue waiting to be processed and added to the vector database
