### ISSUE TITLE
[Server] - Simple Task Queue Operations

### ISSUE THREAD

**Issue by SamratSahoo** [gtfintechlab/Universal-NFT-Vector-Database#4]
## What / Why?
There are many parts of this application that are computationally intensive (i.e. converting images into vectors) and therefore cannot be handled in a single API request alone. 

That's why we need a task queue to handle these computationally intensive parts. We can use something like Amazon Simple Queue Service to do this but it would be much easier to simply mimic a task queue using Firebase and an external python script. This issue handles add operation of the task queue.

## Acceptance Criteria
**Firebase Criteria:**
- [x] Create a collection called `task_queue` in Firebase
- [ ] Create a collection called `checkpoints` in Firebase and a document with an id `task_queue`
- [ ] Create a field in the `task_queue` document called `queue` with a type of list
- [ ] Create a field in the `task_queue` document called `failed` with a type of list

**ExpressJS / Server Criteria:**
- [x] Write an API Endpoint that will add data (a new document) to the `task_queue` collection --> Ensure added data adheres to the task queue item Model Provided. This will also add the id of the Task Queue Item to the `queue` field in the `task_queue` document in the `checkpoints` collection. 
 - API Route: `/api/taskQueue/add`
 - Request Body: 
```
{ 
    data: Object // data is a dictionary that follows the TaskQueueItem Model
}
```
   - Successful Response:
```
// 200 Status Code
{ 
    success: boolean,
    data: Object         // data that was added to the task queue
}
```
-  Failed Response:
```
//  400 Access Code
{
    success: boolean,
    error: string
}
```

## Models
**Task Queue Item:**
```
TaskQueueItem{
    id: string,
    type: string,
    import: Date,
    data: Object        // Object refers to a dictionary / JSON Data
}
```
## Notes
- Cover edge cases / potential errors as you see fit; add comments when covering these so I know what each case is. We will modify these cases when reviewing code
