### ISSUE TITLE
[Milvus] - Task Queue Python Script

### ISSUE THREAD

**Issue by SamratSahoo** [gtfintechlab/Universal-NFT-Vector-Database#7]
## What / Why? 

Some of our operations are computationally heavy. We need a task queue that will read from the task_queue collection on Firebase and perform the necessary operations based on the type (either `contract` or `NFT`) and then write back to Firebase. The task queue will essentially be one method with a `while True`. All code for the task queue should be written in `milvus/task_queue.py`

I **highly** recommend this be modularized into multiple methods to handle the different cases (i.e. handle contract vs NFT)

## Acceptance Criteria
**General Acceptance Criteria**:
- [x] Create a `main` method and a `while True` loop inside the main method
- [x] Read the top element in the `queue` field in the `task_queue` document in the `checkpoints` collection and remove it
- [x] Query the `task_queue` collection for the task queue item with this id
- [x] Check the type of the task queue item for if it is a `contract` or a `NFT`
- [x] If on failure, add the item back to the task_queue and add the task queue item id to the `failed` field in the `task_queue` document in the `checkpoints` collection

**Contract Acceptance Criteria**:
- If it is a contract, we need to gather all of the associated NFTs and their media files
- [x] Use Alchemy API to gather all associated NFTs and their media files 
 - An example of the API being used in Javascript can be found [here](https://github.com/gtfintechlab/blockchain-crypto-defi-spring-2022/blob/main/nft-vector-dataset/main.js)
 - You will need to do something similar with the API requests in Python
- [x] For each NFT of each contract, add a new item to the task queue --> make sure all NFTs added follow the NFT model. The NFT information will go in the data field of the Task Queue Item
- [x] Add the contract to the `all_contracts` and `erc_721_ethereum_contracts` collection of Firebase

**NFT Acceptance Criteria**:
- If it is a NFT, we need to convert the media file into a vector and add it to the vector database; `milvus.py` and `vector.py` provide useful methods + examples on how to do this
- [x] Read the media file as a Pillow Image
- [x] Convert the image to a binary vector
- [x] Add the image to Milvus
- [x] Add the NFT information to the `all_nfts` and `erc_721_ethereum_nfts` collection on Firebase

## Models
**Task Queue Item:**
```
TaskQueueItem{
    id: string,
    type: string,
    import: Date,
    data: Object        // Object refers to a dictionary / JSON Data
}
```

**Contract**:
```
Contract{
    id: string,
    address: string,
    name: string,
}
```

**NFT**:
```
NFT {
    id: string, 
    transactionId: string,
    contractAddress: string,
    mintTime: Date,
    tokenId: number,
    owner: string, 
    tokenURI: string,
}
```
